raszi/node-tmp

- lib/tmp.js
- fixes #17:unwound recursive calls into a simple loop
The only problem that remains is that of available memory if the user managed to create so many directories and subdirectories that we eat up the memory while pushing the strings unto the stack...
> Fix for #17

- lib/tmp.js
- package.json
> fix(windows): fix tempDir on windows

- lib/tmp.js
- test/base.js
- test/dir-sync-test.js
- test/dir-test.js
- test/issue62-sync.js
- test/issue62.js
- test/unsafe-sync.js
Detailed explanation: https://github.com/raszi/node-tmp/issues/62
> Fix issue 62; duplicate delete for _rmdirRecursiveSync

- lib/tmp.js
We are pushing the `_cleanupCallback` wrapper into `_removeObjects`,
not the original `removeFunction`.
---------
I'm very unfamiliar with vows.js, so I'm submitting this without a test case - sorry! Inserting some `console.log` debug statements indicates that it fixes the problem though.
> Prune `_removeObjects` correctly

- lib/tmp.js
Use fs.stat() and fs.statSync() instead of deprecated fs.exists()
and fs.existsSync().
> Replace calls to deprecated fs API functions

- lib/tmp.js
- package.json
Changed the way how _removeObjects is being looped in function _garbageCollector, each function in the array should be called once (keeping in mind the fact that the function itself modifies _removeObjects array).
Writing a test case for reproducing the problem, and checking the correct behavior is somewhat difficult, because the carbage collection is being run only at process exit. No test cases were added/changed, because that would require significant changes to how the test cases are being run.
> Fix for garbage collector, issue #97

- lib/tmp.js
- package.json
> Get builtin fs, errno constants in both node 4 and node 6

- README.md
- lib/tmp.js
- test/base.js
- test/file-test.js
This is a proposed implementation supporting issue #88 and providing a solution to the problem identified in issue #91.  This works on Linux.  I'm unable to test on Windows, and am unsure whether it behaves the same as POSIX systems when a descriptor is kept open after the file is removed.
Let me know if you find this worthwhile, or would like changes made before merging.
Thanks in advance for considering this.
> add options to control descriptor management

- appveyor.yml
Fixes #109.
See examples of failed builds at https://ci.appveyor.com/project/binki/node-tmp
> Add appveyor.yml.

- .gitignore
- .travis.yml
- lib/tmp.js
- package.json
- test/base.js
- test/file-test.js
- test/issue115-file-sync.js
- test/issue115-file.js
Fixes #117
Add node 7 to travis build matrix
Bump version to 0.0.32
> Fixes #115

- README.md
- lib/tmp.js
- test/dir-sync-test.js
- test/dir-test.js
- test/file-sync-test.js
- test/file-test.js
- test/name-test.js
> prepend opts.dir || tmpDir to template if no path is given

- lib/tmp.js
`process.binding()` is an internal API of Node, and
its use should be avoided.
Modern versions of Node have `constants` properties
on the individual public modules, so using these
and falling back to the `process.binding()` path
ensures that this module is unaffected by
changes to Node’s internals.
> Avoid relying on Node’s internals

- .travis.yml
- appveyor.yml
- lib/tmp.js
- package-lock.json
- package.json
- According to [issue 158](https://github.com/raszi/node-tmp/issues/158), remove test for node 0.10, 0.12, 4, 5, 7 since [they are not alive](https://github.com/nodejs/Release#nodejs-release-working-group)
- Use `os.tmpdir` instead of os-tmpdir package
- Update devDependencies since we are going to drop support for node 4.x
Haven't change too much :)
> Bump node version

- lib/tmp.js
IDEs like WebStorm/IntelliJ supports jsdoc blocks to add ability to code completion and typechecking.
Thus, the missing `unsafeCleanup` option in jsdoc forces the IDE to highlight the `tmp.dir({ unsafeCleanup: true }, ...)` calls as an error.
> Add `unsafeCleanup` option to jsdoc

- lib/tmp.js
`{postfix :""}` gives filename without file extension.
> fix #182 fileSync takes empty string postfix option

- README.md
> fix gh-179: template no longer accepts arbitrary paths

- package.json
- test/file-sync-test.js
- test/file-test.js
chore: update rimraf to latest version
chore: remove duplicate dependencies section from package.json
> test: add missing tests for #182

- lib/tmp.js
- package.json
- test/dir-test.js
- test/name-sync-test.js
- test/name-test.js
Fixes #176.
This will cause `_generateTmpName` to fail early if both `opts.dir` and `tmpDir` are undefined.
> fix: fail early if there is no tmp dir specified

- README.md
- lib/tmp.js
- test/child-process.js
chore(docs): add info about compatibility on signal handling
> HOTFIX #187: restore behaviour for #182

- lib/tmp.js
- test/issue121-test.js
- test/issue129-sigint-test.js
- test/issue129-test.js
- test/outband/issue121.js
- test/outband/issue129-sigint.js
- test/outband/issue129.js
@raszi this fix requires a new release :)
~we might have to add information to the docs that tmp will install signal handlers for SIGINT, which basically will keep the application running unless the user installs sigint handlers on his own.~
I have added a guard so that tmp will detect any user installed sigint listeners, and if there are none, tmp will exit the process.
> fix #192: tmp must not exit the process on its own

- lib/tmp.js
- package.json
The `rimraf` dependency is [out of date](https://david-dm.org/raszi/node-tmp), and so are some of the `devDependencies`. This PR updates the dependencies to the latest version.
> Update dependencies to latest versions

- .travis.yml
- appveyor.yml
- lib/tmp.js
- package.json
- test/dir-sync-test.js
- test/file-sync-test.js
- test/inband-standard.js
internally, we still use the synchronous remove functions on process exit.
> fix #197: return sync callback when using the sync interface, otherwise return the async callback

- lib/tmp.js
- test/assertions.js
- test/child-process.js
- test/dir-test.js
- test/file-test.js
- test/inband-standard.js
- test/issue121-test.js
- test/outband/issue121.js
- test/outband/issue129-sigint.js
only tmp- prefixed names must be used
remove unused imports
fix linting problems
fix octal number literals
add missing comments
> fix #214: refactor tests and lib

- test/name-inband-standard.js
the name option test was already there but got never invoked.
the name option was tested indirectly though via standard inband tests for file and dir, both async and sync.
> fix #212: enable direct name option test

- lib/tmp.js
- must call either rimraf.sync or rmdirSync during garbage collection and not use a next parameter
- remove rimraf wrappers, one can directly call the functions and the wrappers do not make any sense
> fix #230: regression after fix for #197

- .gitignore
- CHANGELOG.md
- appveyor.yml
- package.json
- scripts/prepare-changelog.sh
fix #191: generate changelog from pull requests using lerna-changelog
@raszi 
Prior to publishing a new release, the changelog must be updated.
To do this, simply run `./scripts/prepare-changelog.sh <previous-version-tag>`.
This will create a CHANGELOG.new.md based on the old CHANGELOG.md.
Normally, this will give you an unreleased new version at the very top.
Here you must insert the actual version number.
After review, simply move the CHANGELOG.new.md to CHANGELOG.md and you are done.
Have fun.
> fix #191: generate changelog from pull requests using lerna-changelog
